name: 'recomendacao_projetos'
version: '1.0.0'

profile: 'recomendacao_projetos'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

vars:
  "dbt_date:time_zone": "America/Sao_Paulo"

clean-targets:
  - "target"
  - "dbt_packages"

models:
  recomendacao_projetos:
    staging:              # -> bronze
      +schema: bronze
      +materialized: view
    
    intermediate:         # -> silver
      +schema: silver
      +materialized: view
    
    mart:                 # -> gold
      +schema: gold
      +materialized: table
